In [1]:
import pandas as pd
import numpy as np
data=pd.read_csv('Desktop/StudentsPerformance.csv')
data

gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard   
1    female        group C                some college      standard   
2    female        group B             master's degree      standard   
3      male        group A          associate's degree  free/reduced   
4      male        group C                some college      standard   
..      ...            ...                         ...           ...   
995  female        group E             master's degree      standard   
996    male        group C                 high school  free/reduced   
997  female        group C                 high school  free/reduced   
998  female        group D                some college      standard   
999  female        group D                some college  free/reduced   

    test preparation course  math score  reading score  writing score  
0                      none          72             72             74  
1                 completed          69             90             88  
2                      none          90             95             93  
3                      none          47             57             44  
4                      none          76             78             75  
..                      ...         ...            ...            ...  
995               completed          88             99             95  
996                    none          62             55             55  
997               completed          59             71             65  
998               completed          68             78             77  
999                    none          77             86             86  

[1000 rows x 8 columns]

In [2]:
grouped=data.groupby('race/ethnicity')
grouped.get_group('group A')

gender race/ethnicity parental level of education         lunch  \
3      male        group A          associate's degree  free/reduced   
13     male        group A                some college      standard   
14   female        group A             master's degree      standard   
25     male        group A             master's degree  free/reduced   
46   female        group A          associate's degree      standard   
..      ...            ...                         ...           ...   
974  female        group A                some college      standard   
983  female        group A                some college      standard   
985    male        group A                 high school      standard   
988  female        group A            some high school  free/reduced   
994    male        group A                 high school      standard   

    test preparation course  math score  reading score  writing score  
3                      none          47             57             44  
13                completed          78             72             70  
14                     none          50             53             58  
25                     none          73             74             72  
46                completed          55             65             62  
..                      ...         ...            ...            ...  
974                    none          54             63             67  
983               completed          78             87             91  
985                    none          57             51             54  
988                    none          44             45             45  
994                    none          63             63             62  

[89 rows x 8 columns]

In [3]:
group=data.groupby('lunch')
group.get_group('standard')

gender race/ethnicity parental level of education     lunch  \
0    female        group B           bachelor's degree  standard   
1    female        group C                some college  standard   
2    female        group B             master's degree  standard   
4      male        group C                some college  standard   
5    female        group B          associate's degree  standard   
..      ...            ...                         ...       ...   
987    male        group E            some high school  standard   
991  female        group B            some high school  standard   
994    male        group A                 high school  standard   
995  female        group E             master's degree  standard   
998  female        group D                some college  standard   

    test preparation course  math score  reading score  writing score  
0                      none          72             72             74  
1                 completed          69             90             88  
2                      none          90             95             93  
4                      none          76             78             75  
5                      none          71             83             78  
..                      ...         ...            ...            ...  
987               completed          81             75             76  
991               completed          65             82             78  
994                    none          63             63             62  
995               completed          88             99             95  
998               completed          68             78             77  

[645 rows x 8 columns]

In [4]:
grouped.count()

gender  parental level of education  lunch  \
race/ethnicity                                               
group A             89                           89     89   
group B            190                          190    190   
group C            319                          319    319   
group D            262                          262    262   
group E            140                          140    140   

                test preparation course  math score  reading score  \
race/ethnicity                                                       
group A                              89          89             89   
group B                             190         190            190   
group C                             319         319            319   
group D                             262         262            262   
group E                             140         140            140   

                writing score  
race/ethnicity                 
group A                    89  
group B                   190  
group C                   319  
group D                   262  
group E                   140

In [5]:
grouped.sum()

math score  reading score  writing score
race/ethnicity                                          
group A               5485           5756           5578
group B              12056          12797          12464
group C              20564          22044          21637
group D              17649          18348          18378
group E              10335          10224           9997

In [6]:
grouped.mean()

math score  reading score  writing score
race/ethnicity                                          
group A          61.629213      64.674157      62.674157
group B          63.452632      67.352632      65.600000
group C          64.463950      69.103448      67.827586
group D          67.362595      70.030534      70.145038
group E          73.821429      73.028571      71.407143

In [7]:
males_marks=np.array([57,89,75,68,94])

males_marks

array([57, 89, 75, 68, 94])

In [8]:
females_marks=np.array([86,79,68,95,92])
females_marks

array([86, 79, 68, 95, 92])

In [9]:
np.cov(males_marks,females_marks)

array([[229.3 ,  -7.75],
       [ -7.75, 117.5 ]])

In [10]:
np.corrcoef(males_marks,females_marks)

array([[ 1.        , -0.04721508],
       [-0.04721508,  1.        ]])

In [11]:
males_marks.sum()

383

In [12]:
females_marks.mean()

84.0

In [13]:
np.percentile(females_marks,50)

86.0

In [14]:
np.percentile(males_marks,60)

80.6

In [17]:
# sum of all numbers in a 2D array
arr=np.array([[12,15,24],[16,85,45],[25,10,62]])
arr.sum()

294

In [18]:
# 50 percentile
np.percentile(arr,50)

24.0

In [19]:
# minimum and maximum value
arr.min()

10

In [20]:
arr.max()

85

In [21]:
# access all the elements of array except first one
arr=np.array([15,45,56,62,47,20])
print(arr[1:])

[45 56 62 47 20]


In [22]:
# addition of matrix
a=np.array([12,14,16])
b=np.array([20,45,82])
a+b

array([32, 59, 98])

In [23]:
#return all the elements of the series
s=pd.Series([1,15,40,20,27,46,35])
s

0     1
1    15
2    40
3    20
4    27
5    46
6    35
dtype: int64

In [24]:
#first three element of the series
print(s[0:3])

0     1
1    15
2    40
dtype: int64


In [26]:
#last element of the series
print(s[6])

35


In [27]:
#return all elements of the series execpt last two element
print(s[:5])

0     1
1    15
2    40
3    20
4    27
dtype: int64


In [28]:
#return all elements of the series execpt last  element
print(s[:6])

0     1
1    15
2    40
3    20
4    27
5    46
dtype: int64


In [29]:
#return last two elements of the series
print(s[5:])

5    46
6    35
dtype: int64
